server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://52.78.80.77:3306/donkey?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8
    username: root
    password: donkey!@#

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: create
        show_sql: true
        format_sql: true
        use_sql_comments: true
    show-sql: true
    generate-ddl: true
    open-in-view: false

logging.level:
  org.hibernate.type.descriptor.sql: TRACE
  org.springframework:
    security: DEBUG
  root: info