spring:
  mail:
    host: smtp.gmail.com
    port: 587
    default-encoding: UTF-8
    username: edangnagwi@gmail.com
    password: qwer12345678!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true