server:
  port: 8081

spring:
  profiles:
    include: oauth, stmp

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://52.78.80.77:3306/donkey?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8
    username: root
    password: donkey!@#

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    show-sql: true
    generate-ddl: true
    open-in-view: false

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    check-template-location: true

  jwt:
    secret: ehd21zldo6n8key9rjf0xle4hd234zlW567kddlqslek

  cache:
    type: redis

  redis:
    host: localhost # donkey 서버
    port: 6379
    password: donkey

logging.level:
  org.hibernate.type.descriptor.sql: error
  org.springframework:
    security: error
  root: info